services:
  astro-web:
    build: .
    container_name: atrahdis-web
    restart: unless-stopped
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro-web.rule=Host(`atrahdis.id`) || Host(`www.atrahdis.id`) || Host(`new.atrahdis.id`)"
      - "traefik.http.routers.astro-web.entrypoints=websecure"
      - "traefik.http.routers.astro-web.tls.certresolver=mytlschallenge"
      - "traefik.http.services.astro-web.loadbalancer.server.port=4321"

networks:
  default:
    name: root_default
    external: true